name: wdio-test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
        - uses: nanasess/setup-chromedriver@v1
        # set up virtual display env for chromedriver to run in
        - run: |
            export DISPLAY=:99
            chromedriver --url-base=/wd/hub &
            sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional        
        - run: npm install
        - run: npm run wdio